version: "3.8"

services:
  redis:
    image: "redis:7-alpine"
    command: ["redis-server", "--requirepass km111", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - "E:\\base-python\\redis:/data"
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - app_network

  postgres:
    image: "timescale/timescaledb:2.25.2-pg17"
    restart: always
    environment:
      POSTGRES_PASSWORD: km111
      POSTGRES_USER: test
      POSTGRES_DB: base
    ports:
      - "5432:5432"
    volumes:
      - "E:\\base-python\\postgres:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app_network

  rabbitmq:
    image: "rabbitmq:4.0.2-management"
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: km111
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - "E:\\base-python\\rabbitmq:/var/lib/rabbitmq"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app_network

  web:
    image: base-python:1.0
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8080 --workers 4
    depends_on:
      - redis
      - postgres
    ports:
      - "8099:8099"
      - "8080:8080"
    volumes:
      - "./:/app"
    environment:
      - TZ=Asia/Shanghai
    networks:
      - app_network

  taskiq-worker:
    image: base-python:1.0
    build:
      context: .
      dockerfile: Dockerfile
    command: taskiq worker -m app.core.taskiq_broker_factory:get_broker_for_default
    environment:
      - TZ=Asia/Shanghai
    depends_on:
      - rabbitmq
      - redis
      - postgres
    volumes:
      - "./:/app"
    networks:
      - app_network

  taskiq-worker-high:
    image: base-python:1.0
    build:
      context: .
      dockerfile: Dockerfile
    command: taskiq worker -m app.core.taskiq_broker_factory:get_broker_for_high
    environment:
      - TZ=Asia/Shanghai
    depends_on:
      - rabbitmq
      - redis
    volumes:
      - "./:/app"
    networks:
      - app_network

  taskiq-worker-low:
    image: base-python:1.0
    build:
      context: .
      dockerfile: Dockerfile
    command: taskiq worker -m app.core.taskiq_broker_factory:get_broker_for_low
    environment:
      - TZ=Asia/Shanghai
    depends_on:
      - rabbitmq
      - redis
    volumes:
      - "./:/app"
    networks:
      - app_network

  taskiq-scheduler:
    image: base-python:1.0
    build:
      context: .
      dockerfile: Dockerfile
    command: taskiq scheduler -m app.core.taskiq:scheduler
    depends_on:
      - rabbitmq
      - redis
      - postgres
    volumes:
      - "./:/app"
    environment:
      - TZ=Asia/Shanghai
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
