"""update_research_report_record

Revision ID: 24dd1f661250
Revises: a94a672f589e
Create Date: 2026-03-31 15:46:35.710761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '24dd1f661250'
down_revision: Union[str, None] = 'a94a672f589e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('industry_research_report_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('report_summary', sa.Text(), nullable=True, comment='整篇研报摘要'))
        batch_op.alter_column('process_start',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_comment='开始处理时间',
               existing_nullable=True)
        batch_op.alter_column('process_end',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_comment='结束处理时间',
               existing_nullable=True)

    with op.batch_alter_table('stock_research_report_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('report_summary', sa.Text(), nullable=True, comment='整篇研报摘要'))
        batch_op.alter_column('process_start',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_comment='开始处理时间',
               existing_nullable=True)
        batch_op.alter_column('process_end',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_comment='结束处理时间',
               existing_nullable=True)
        batch_op.drop_column('content')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_research_report_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True, comment='内容'))
        batch_op.alter_column('process_end',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_comment='结束处理时间',
               existing_nullable=True)
        batch_op.alter_column('process_start',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_comment='开始处理时间',
               existing_nullable=True)
        batch_op.drop_column('report_summary')

    with op.batch_alter_table('industry_research_report_record', schema=None) as batch_op:
        batch_op.alter_column('process_end',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_comment='结束处理时间',
               existing_nullable=True)
        batch_op.alter_column('process_start',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_comment='开始处理时间',
               existing_nullable=True)
        batch_op.drop_column('report_summary')

    # ### end Alembic commands ###
