"""init

Revision ID: 3d703d6ce3a8
Revises: 
Create Date: 2026-03-10 14:16:44.772029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d703d6ce3a8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attachments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('type', sa.Enum('FILE', 'URL', 'OBJECT_STORAGE', name='attachmenttypeenum'), nullable=False, comment='附件类型'),
    sa.Column('original_filename', sa.String(length=255), nullable=False, comment='原始文件名'),
    sa.Column('stored_filename', sa.String(length=255), nullable=False, comment='存储文件名'),
    sa.Column('file_path', sa.String(length=255), nullable=True, comment='文件路径'),
    sa.Column('file_size', sa.Integer(), nullable=True, comment='文件大小'),
    sa.Column('mime_type', sa.String(length=100), nullable=False, comment='MIME类型'),
    sa.Column('uploader_id', sa.Integer(), nullable=True, comment='上传者ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('checksum', sa.String(length=32), nullable=True, comment='校验和'),
    sa.Column('datas', sa.LargeBinary(), nullable=True, comment='数据'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attachments_checksum'), ['checksum'], unique=False)
        batch_op.create_index(batch_op.f('ix_attachments_uploader_id'), ['uploader_id'], unique=False)

    op.create_table('dead_letter_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False, comment='Celery task ID'),
    sa.Column('task_name', sa.String(length=255), nullable=False, comment='任务名称'),
    sa.Column('args', sa.JSON(), nullable=True, comment='位置参数'),
    sa.Column('kwargs', sa.JSON(), nullable=True, comment='关键字参数'),
    sa.Column('exception', sa.Text(), nullable=True, comment='异常信息'),
    sa.Column('traceback', sa.Text(), nullable=True, comment='完整堆栈'),
    sa.Column('failed_at', sa.DateTime(), nullable=False, comment='失败时间'),
    sa.Column('last_retry_at', sa.DateTime(), nullable=True, comment='最后重试时间'),
    sa.Column('retry_count', sa.Integer(), nullable=False, comment='重试次数'),
    sa.Column('max_retries', sa.Integer(), nullable=False, comment='最大重试次数'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='状态: pending/retrying/resolved/failed'),
    sa.Column('queue', sa.String(length=100), nullable=True, comment='原始队列'),
    sa.Column('worker', sa.String(length=100), nullable=True, comment='执行worker'),
    sa.Column('result', sa.Text(), nullable=True, comment='任务执行结果'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dead_letter_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dead_letter_records_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dead_letter_records_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_dead_letter_records_task_id'), ['task_id'], unique=False)

    op.create_table('tenant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('company_name', sa.String(length=40), nullable=True, comment='公司名称'),
    sa.Column('description', sa.Text(), nullable=False, comment='描述'),
    sa.Column('appid', sa.String(length=40), nullable=False, comment='应用id'),
    sa.Column('app_secret', sa.String(length=40), nullable=False, comment='应用密钥'),
    sa.Column('status', sa.Enum('active', 'stopped', name='tenantstatusenum'), nullable=False, comment='状态'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('appid')
    )
    op.create_table('user',
    sa.Column('username', sa.String(length=50), nullable=False, comment='用户名'),
    sa.Column('email', sa.String(length=255), nullable=True, comment='邮箱'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='手机号'),
    sa.Column('nickname', sa.String(length=50), nullable=True, comment='昵称'),
    sa.Column('avatar_id', sa.BigInteger(), nullable=True, comment='头像ID'),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'BANNED', name='userstatusenum'), nullable=False, comment='用户状态'),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True, comment='最后登录时间'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='密码哈希'),
    sa.Column('salt', sa.String(length=100), nullable=False, comment='密码盐'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='是否删除'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间'),
    sa.Column('deleted_by', sa.BigInteger(), nullable=True, comment='删除人ID'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('idx_user_email', ['email'], unique=True)
        batch_op.create_index('idx_user_phone', ['phone'], unique=True)
        batch_op.create_index('idx_user_status', ['status'], unique=False)
        batch_op.create_index('idx_user_username', ['username'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_is_deleted'), ['is_deleted'], unique=False)

    op.create_table('tenant_auth_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('tenant_id', sa.Integer(), nullable=False, comment='租户ID'),
    sa.Column('appid', sa.String(length=40), nullable=True, comment='应用id'),
    sa.Column('refresh_jti', sa.String(length=40), nullable=False, comment='刷新令牌'),
    sa.Column('expire_time', sa.DateTime(timezone=True), nullable=False, comment='过期时间'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tenant_auth_token', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenant_auth_token_appid'), ['appid'], unique=False)
        batch_op.create_index(batch_op.f('ix_tenant_auth_token_refresh_jti'), ['refresh_jti'], unique=False)
        batch_op.create_index(batch_op.f('ix_tenant_auth_token_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant_auth_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenant_auth_token_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_tenant_auth_token_refresh_jti'))
        batch_op.drop_index(batch_op.f('ix_tenant_auth_token_appid'))

    op.drop_table('tenant_auth_token')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_is_deleted'))
        batch_op.drop_index('idx_user_username')
        batch_op.drop_index('idx_user_status')
        batch_op.drop_index('idx_user_phone')
        batch_op.drop_index('idx_user_email')

    op.drop_table('user')
    op.drop_table('tenant')
    with op.batch_alter_table('dead_letter_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dead_letter_records_task_id'))
        batch_op.drop_index(batch_op.f('ix_dead_letter_records_status'))
        batch_op.drop_index(batch_op.f('ix_dead_letter_records_id'))

    op.drop_table('dead_letter_records')
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attachments_uploader_id'))
        batch_op.drop_index(batch_op.f('ix_attachments_checksum'))

    op.drop_table('attachments')
    # ### end Alembic commands ###
