"""update_research_report_record

Revision ID: 65603fd400c5
Revises: 24dd1f661250
Create Date: 2026-04-07 13:43:22.188549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65603fd400c5'
down_revision: Union[str, None] = '24dd1f661250'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_research_report_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('industry_name', sa.String(length=32), nullable=True, comment='行业名称（一级行业）'))
        batch_op.create_index(batch_op.f('ix_stock_research_report_record_industry_name'), ['industry_name'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_research_report_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_research_report_record_industry_name'))
        batch_op.drop_column('industry_name')

    # ### end Alembic commands ###
