"""add_report_process_record

Revision ID: a94a672f589e
Revises: 3d703d6ce3a8
Create Date: 2026-03-17 17:41:57.591817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a94a672f589e'
down_revision: Union[str, None] = '3d703d6ce3a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('industry_research_report_record',
    sa.Column('report_id', sa.Integer(), nullable=False, comment='研报ID'),
    sa.Column('filename', sa.String(length=256), nullable=False, comment='文件名'),
    sa.Column('file_path', sa.String(length=500), nullable=False, comment='文件路径'),
    sa.Column('trade_date', sa.Date(), nullable=False, comment='发布时间'),
    sa.Column('industry_name', sa.String(length=32), nullable=True, comment='行业名称'),
    sa.Column('org_name', sa.String(length=128), nullable=True, comment='发布组织'),
    sa.Column('org_code', sa.String(length=32), nullable=True, comment='组织代码'),
    sa.Column('info_code', sa.String(length=32), nullable=True, comment='研报获取关键字段'),
    sa.Column('process_start', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='开始处理时间'),
    sa.Column('process_end', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='结束处理时间'),
    sa.Column('process_status', sa.Enum('no', 'pdf_analyzed', 'image_analyzed', 'integrated', 'chunked', 'chunked_to_db', 'failed', name='processstatusenum'), nullable=True, comment='处理状态'),
    sa.Column('output_path', sa.String(length=500), nullable=True, comment='文件路径'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='是否删除'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间'),
    sa.Column('deleted_by', sa.BigInteger(), nullable=True, comment='删除人ID'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('industry_research_report_record', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_industry_research_report_record_industry_name'), ['industry_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_industry_research_report_record_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_industry_research_report_record_process_status'), ['process_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_industry_research_report_record_report_id'), ['report_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_industry_research_report_record_trade_date'), ['trade_date'], unique=False)

    op.create_table('stock_research_report_record',
    sa.Column('report_id', sa.Integer(), nullable=False, comment='研报ID'),
    sa.Column('filename', sa.String(length=256), nullable=False, comment='文件名'),
    sa.Column('file_path', sa.String(length=500), nullable=False, comment='文件路径'),
    sa.Column('trade_date', sa.Date(), nullable=False, comment='发布时间'),
    sa.Column('ts_code', sa.String(length=16), nullable=False, comment='股票代码，统一字段'),
    sa.Column('symbol', sa.String(length=16), nullable=True, comment='股票代码，不带后缀'),
    sa.Column('company_name', sa.String(length=32), nullable=True, comment='股票名称'),
    sa.Column('org_name', sa.String(length=128), nullable=True, comment='发布组织'),
    sa.Column('org_code', sa.String(length=32), nullable=True, comment='组织代码'),
    sa.Column('info_code', sa.String(length=32), nullable=True, comment='研报获取关键字段'),
    sa.Column('content', sa.Text(), nullable=True, comment='内容'),
    sa.Column('process_start', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='开始处理时间'),
    sa.Column('process_end', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='结束处理时间'),
    sa.Column('process_status', sa.Enum('no', 'pdf_analyzed', 'image_analyzed', 'integrated', 'chunked', 'chunked_to_db', 'failed', name='processstatusenum'), nullable=True, comment='处理状态'),
    sa.Column('output_path', sa.String(length=500), nullable=True, comment='文件路径'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='是否删除'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间'),
    sa.Column('deleted_by', sa.BigInteger(), nullable=True, comment='删除人ID'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock_research_report_record', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_research_report_record_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_research_report_record_process_status'), ['process_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_research_report_record_report_id'), ['report_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_research_report_record_trade_date'), ['trade_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_research_report_record_ts_code'), ['ts_code'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_research_report_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_research_report_record_ts_code'))
        batch_op.drop_index(batch_op.f('ix_stock_research_report_record_trade_date'))
        batch_op.drop_index(batch_op.f('ix_stock_research_report_record_report_id'))
        batch_op.drop_index(batch_op.f('ix_stock_research_report_record_process_status'))
        batch_op.drop_index(batch_op.f('ix_stock_research_report_record_is_deleted'))

    op.drop_table('stock_research_report_record')
    with op.batch_alter_table('industry_research_report_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_industry_research_report_record_trade_date'))
        batch_op.drop_index(batch_op.f('ix_industry_research_report_record_report_id'))
        batch_op.drop_index(batch_op.f('ix_industry_research_report_record_process_status'))
        batch_op.drop_index(batch_op.f('ix_industry_research_report_record_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_industry_research_report_record_industry_name'))

    op.drop_table('industry_research_report_record')
    # ### end Alembic commands ###
