version: '3.8'

services:
  redis:
    extends:
      file: infra.yml
      service: redis

  postgres:
    extends:
      file: infra.yml
      service: postgres

  openresty:
    extends:
      file: app.yml
      service: openresty

  fastapi:
    extends:
      file: app.yml
      service: fastapi

  taskiq-worker:
    extends:
      file: app.yml
      service: taskiq-worker

  taskiq-scheduler:
    extends:
      file: app.yml
      service: taskiq-scheduler